# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  test_and_pack:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          name: "Run Application Tests"
          command: "dotnet test"
      - run:
          name: "Pack the Main Class Library"
          command: "dotnet pack -c Release /p:Version=1.0.${CIRCLE_BUILD_NUM} ./RozaMin.ISO3166/RozaMin.ISO3166.csproj"
      - when:
          condition:
            equal: ["master", << pipeline.git.branch >>]
          steps:
            - run:
                name: "Publish Package to Nuget.org"
                command: "echo BEGIN${NUGET_API_KEY}"
            


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test-and-pack-workflow:
    jobs:
      - test_and_pack
