version: 2.1

jobs:
  test_and_pack:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          name: "Run Application Tests"
          command: "dotnet test"
      - run:
          name: "Pack the Main Class Library"
          command: "dotnet pack -c Release /p:Version=1.0.${CIRCLE_BUILD_NUM} ./RozaMin.ISO3166/RozaMin.ISO3166.csproj"
      - run: "dotnet publish -c Release ./RozaMin.ISO3166.Benchmarks/RozaMin.ISO3166.Benchmarks.csproj"
      - run: "dotnet ./RozaMin.ISO3166.Benchmarks/bin/Release/net6.0/RozaMin.ISO3166.Benchmarks.dll"
      - store_artifacts:
          path: ./BenchmarkDotNet.Artifacts
      - when:
          condition:
            equal: ["master", << pipeline.git.branch >>]
          steps:
            - run:
                name: "Publish Package to Nuget.org"
                command: "dotnet nuget push ./RozaMin.ISO3166/bin/Release/RozaMin.ISO3166.1.0.${CIRCLE_BUILD_NUM}.nupkg -k ${NUGET_API_KEY} -s https://api.nuget.org/v3/index.json"

workflows:
  test-and-pack-workflow:
    jobs:
      - test_and_pack:
          context:
            - MainContext
